version: '3.9'

services:
  mongo:
    image: mongo:4.2
    container_name: openhim-mongo
    ports:
      - "27017:27017"
    networks:
      - cht-net
    
  openhim-core:
    container_name: openhim-core
    image: jembi/openhim-core:7
    environment:
      - mongo_url=mongodb://mongo/openhim
      - mongo_atnaUrl=mongodb://mongo/openhim
    ports:
      - "8080:8080"
      - "5000:5000"
      - "5001:5001"
      - "5050:5050"
      - "5051:5051"
      - "5052:5052"
      - "7788:7788"
    depends_on:
      - mongo
    networks:
      - cht-net
  
  openhim-console:
    container_name: openhim-console
    image: jembi/openhim-console:1.14.4
    ports:
        - "9000:80"
    volumes:
      - ./default.json:/usr/share/nginx/html/config/default.json
    depends_on:
      - openhim-core
    networks:
      - cht-net
  
  hapi-fhir:
    container_name: hapi-fhir
    image: hapiproject/hapi:v5.5.1
    environment:
      - spring.datasource.url=jdbc:postgresql://hapi-db:5432/hapi
      - spring.datasource.username=admin
      - spring.datasource.password=instant101
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
      - hapi.fhir.allow_external_references=true
      - hapi.fhir.bulk_export_enabled=true
      - hapi.fhir.subscription.resthook_enabled=true
      - JAVA_TOOL_OPTIONS=-Xmx2g
      - CATALINA_OPTS=-Xmx2g
    depends_on:
      - hapi-db
    networks:
      - cht-net

  hapi-db:
    container_name: hapi-db
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: instant101
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    volumes:
      - 'hapi-db-volume:/var/lib/postgresql/data'
    networks:
      - cht-net

volumes:
  mongo:
  hapi-db-volume:
